# SU(2) Matrix Model, $\Lambda =4$: Result Preprocessing

Notebook created by HLD for the work arXiv: 2503.13368 [quant-ph, hep-th]

In this notebook, we select the best results from different VQE reruns with different Estimator seeds.

In [1]:
import sys
sys.path.append('../../utility')
from L4_evop_data_collate import *

E_02 = 3.13406
E_05 = 3.29894
E_10 = 3.52625
E_20 = 3.89548

# l =0.2

In [2]:
#Correct results
df_l02 = pd.read_csv('results/l0.2_last_val_best.csv')
df_l02.set_index('name', inplace = True)

df_l02_c = pd.read_csv('results/l_02_cobyla_curves_values.csv')
df_l02_s = pd.read_csv('results/l_02_spsa_curves_values.csv')

In [3]:
df_02c_225 = load_drop('results_seeds/l4_l02_op_ev_20_30_40_indv_cobyla_seed225.csv')
df_02s_225 = load_drop('results_seeds/l4_l02_op_ev_20_30_40_indv_spsa_seed225.csv')
df_02c_170 = load_drop('results_seeds/l4_l02_op_ev_20_30_40_indv_cobyla.csv')
df_02s_170 = load_drop('results_seeds/l4_l02_op_ev_20_30_40_indv_spsa.csv')
df_l02_hp15_c = pd.read_csv('results_seeds/l4_l02_op_ev_Hp15_cobyla_seeds.csv')

In [7]:
seed_28 = df_l02_hp15_c.seed_28.to_numpy()
nan =[np.nan]*(650-len(seed_28))
seed28 = np.concatenate((seed_28, nan), axis = 0)
df_02c_170['ev_op_Hp15'] = seed28

In [9]:
l02_collate = EvOpAnsatz_data_collate(df_02c_170, df_02c_225, df_02s_170, df_02s_225, 170, 225, E_02, 0.2)

file saved as results_tests/l0.2_last_val_170.csv
file saved as results_tests/l0.2_last_val_225.csv
Checking COBYLA column
ev_op_Hp15: seed_170
ev_op_Hp20: seed_225
ev_op_Hp25: seed_170
ev_op_Hp30: seed_225
ev_op_Hp15_2f: seed_225
ev_op_Hp20_2f: seed_170
ev_op_Hp25_2f: seed_170
ev_op_Hp30_2f: seed_170
Checking SPSA column
ev_op_Hp15: seed_225
ev_op_Hp20: seed_170
ev_op_Hp25: seed_170
ev_op_Hp30: seed_225
ev_op_Hp15_2f: seed_225
ev_op_Hp20_2f: seed_170
ev_op_Hp25_2f: seed_225
ev_op_Hp30_2f: seed_225
file saved as results_tests/l0.2_last_val_best.csv

In [11]:
l02_collate.df_last_best

               cobyla_values  spsa_values
name
ev_op_Hp15           3.27813      3.17320
ev_op_Hp20           3.18835      3.15612
ev_op_Hp25           3.17782      3.14337
ev_op_Hp30           3.21665      3.14084
ev_op_Hp15_2f        3.15952      3.15614
ev_op_Hp20_2f        3.23598      3.19462
ev_op_Hp25_2f        3.33135      3.13421
ev_op_Hp30_2f        3.47127      3.15462

In [13]:
l02_collate.df_last_best - E_02

               cobyla_values  spsa_values
name
ev_op_Hp15           0.14407      0.03914
ev_op_Hp20           0.05429      0.02206
ev_op_Hp25           0.04376      0.00931
ev_op_Hp30           0.08259      0.00678
ev_op_Hp15_2f        0.02546      0.02208
ev_op_Hp20_2f        0.10192      0.06056
ev_op_Hp25_2f        0.19729      0.00015
ev_op_Hp30_2f        0.33721      0.02056

In [15]:
l02_collate.df_c_best.to_csv('results/l_02_cobyla_curves_values.csv')
l02_collate.df_s_best.to_csv('results/l_02_spsa_curves_values.csv')

## l = 0.5

In [17]:
#Correct results
df_l05 = pd.read_csv('results/l0.5_last_val_best.csv')
df_l05_c = pd.read_csv('results/l_05_cobyla_curves_values.csv')
df_l05_s = pd.read_csv('results/l_05_spsa_curves_values.csv')
df_l05.set_index('name', inplace = True)

In [31]:
df_05c_128 = load_drop('results_seeds/l4_l05_op_ev_20_30_40_indv_cobyla_seed128.csv')
df_05s_128 = load_drop('results_seeds/l4_l05_op_ev_20_30_40_indv_spsa_seed128.csv')
df_05c_170 = load_drop('results_seeds/l4_l05_op_ev_20_30_40_indv_cobyla.csv')
df_05s_170 = load_drop('results_seeds/l4_l05_op_ev_20_30_40_indv_spsa.csv')

In [91]:
df_05c_hp20 = pd.read_csv('results_seeds/l4_l05_op_ev_Hp20_cobyla_seeds.csv')
for i in range(len(df_05c_hp20.columns[1:])):
    print(df_05c_hp20.columns[1:][i], np.round(df_05c_hp20[df_05c_hp20.columns[1:][i]].dropna().to_numpy()[-1],5))

seed_28 7.64992
seed_170 3.35601
seed_225 3.26691
seed_188 3.26351
seed_18 10.39987
seed_38 5.00073
seed_48 4.88799
seed_58 5.2537

In [93]:
ss = df_05c_hp20.seed_170.to_numpy()
nan =[np.nan]*(650-len(ss))
sss = np.concatenate((ss, nan), axis = 0)
df_05c_170['ev_op_Hp20'] = sss

In [95]:
l05_collate = EvOpAnsatz_data_collate(df_05c_170, df_05c_128, df_05s_170, df_05s_128, 170, 128, E_05, 0.5)

file saved as results_tests/l0.5_last_val_170.csv
file saved as results_tests/l0.5_last_val_128.csv
Checking COBYLA column
ev_op_Hp15: seed_128
ev_op_Hp20: seed_170
ev_op_Hp25: seed_170
ev_op_Hp30: seed_128
ev_op_Hp15_2f: seed_170
ev_op_Hp20_2f: seed_170
ev_op_Hp25_2f: seed_170
ev_op_Hp30_2f: seed_128
Checking SPSA column
ev_op_Hp15: seed_170
ev_op_Hp20: seed_128
ev_op_Hp25: seed_170
ev_op_Hp30: seed_170
ev_op_Hp15_2f: seed_128
ev_op_Hp20_2f: seed_170
ev_op_Hp25_2f: seed_128
ev_op_Hp30_2f: seed_128
file saved as results_tests/l0.5_last_val_best.csv

In [97]:
l05_collate.df_last_best

               cobyla_values  spsa_values
name
ev_op_Hp15           4.03464      3.41548
ev_op_Hp20           3.35601      3.30692
ev_op_Hp25           3.29968      3.42603
ev_op_Hp30           3.51242      3.30582
ev_op_Hp15_2f        3.30153      3.34375
ev_op_Hp20_2f        3.54492      3.30794
ev_op_Hp25_2f        3.30028      3.29896
ev_op_Hp30_2f        3.77042      3.33945

In [99]:
l05_collate.df_last_best - E_05

               cobyla_values  spsa_values
name
ev_op_Hp15           0.73570      0.11654
ev_op_Hp20           0.05707      0.00798
ev_op_Hp25           0.00074      0.12709
ev_op_Hp30           0.21348      0.00688
ev_op_Hp15_2f        0.00259      0.04481
ev_op_Hp20_2f        0.24598      0.00900
ev_op_Hp25_2f        0.00134      0.00002
ev_op_Hp30_2f        0.47148      0.04051

In [12]:
#l05_collate.df_c_best - df_l05_c

In [101]:
l05_collate.df_c_best.to_csv('results/l_05_cobyla_curves_values.csv')
l05_collate.df_s_best.to_csv('results/l_05_spsa_curves_values.csv')

## l=1.0

In [123]:
#Correct results
df_l10 = pd.read_csv('results/l1.0_last_val_best.csv')
df_l10_c = pd.read_csv('results/l_10_cobyla_curves_values.csv')
df_l10_s = pd.read_csv('results/l_10_spsa_curves_values.csv')
df_l10.set_index('name', inplace = True)

In [125]:
df_10c_170 = load_drop('results_seeds/l4_l10_op_ev_20_30_40_indv_cobyla.csv')
df_10s_170 = load_drop('results_seeds/l4_l10_op_ev_20_30_40_indv_spsa.csv')

df_10c_0 = load_drop('results/l_10_cobyla_curves_values.csv', False)
df_10s_0 =  df_10s_170

In [127]:
l10_collate = EvOpAnsatz_data_collate(df_10c_170, df_10c_0, df_10s_170, df_10s_0, 170, 0, E_10, 1.0)

file saved as results_tests/l1.0_last_val_170.csv
file saved as results_tests/l1.0_last_val_0.csv
Checking COBYLA column
ev_op_Hp15: seed_0
ev_op_Hp20: seed_0
ev_op_Hp25: seed_0
ev_op_Hp30: seed_0
ev_op_Hp15_2f: seed_0
ev_op_Hp20_2f: seed_0
ev_op_Hp25_2f: seed_0
ev_op_Hp30_2f: seed_0
Checking SPSA column
ev_op_Hp15: seed_0
ev_op_Hp20: seed_0
ev_op_Hp25: seed_0
ev_op_Hp30: seed_0
ev_op_Hp15_2f: seed_0
ev_op_Hp20_2f: seed_0
ev_op_Hp25_2f: seed_0
ev_op_Hp30_2f: seed_0
file saved as results_tests/l1.0_last_val_best.csv

In [129]:
l10_collate.df_last_best -E_10

               cobyla_values  spsa_values
name
ev_op_Hp15           0.09457      0.23238
ev_op_Hp20           0.31448     -0.01741
ev_op_Hp25           0.00887     -0.03907
ev_op_Hp30           0.24762      0.01926
ev_op_Hp15_2f        0.82689      0.19140
ev_op_Hp20_2f        0.23373     -0.07086
ev_op_Hp25_2f        1.39991      0.23634
ev_op_Hp30_2f        1.23291      0.18581

In [131]:
df_10c_225 = load_drop('results_seeds/l4_l10_op_ev_cobyla_seed225.csv')
df_10s_225 = load_drop('results_seeds/l4_l10_op_ev_spsa_seed225.csv')

In [139]:
df_10cc = pd.read_csv('results_seeds/l4_l10_op_ev_Hp25_spsa_seeds.csv')
for i in range(len(df_10cc.columns[1:])):
    print(df_10cc.columns[1:][i], np.round(df_10cc[df_10cc.columns[1:][i]].dropna().to_numpy()[-1],5))

seed_28 4.69473
seed_170 3.40026
seed_225 3.5258
seed_188 3.27797
seed_18 7.06349
seed_38 4.38076
seed_48 3.96745
seed_58 3.50736

In [141]:
ss = df_10cc.seed_48.to_numpy()
nan =[np.nan]*(1351-len(ss))
sss = np.concatenate((ss, nan), axis = 0)
df_10s_225['ev_op_Hp25'] = sss

In [143]:
l10_collate_v2 = EvOpAnsatz_data_collate(df_10c_225, df_10c_0, df_10s_225, df_10s_0, 225, 0, E_10, 1.0)

file saved as results_tests/l1.0_last_val_225.csv
file saved as results_tests/l1.0_last_val_0.csv
Checking COBYLA column
ev_op_Hp15: seed_0
ev_op_Hp20: seed_0
ev_op_Hp25: seed_0
ev_op_Hp30: seed_0
ev_op_Hp15_2f: seed_0
ev_op_Hp20_2f: seed_0
ev_op_Hp25_2f: seed_0
ev_op_Hp30_2f: seed_0
Checking SPSA column
ev_op_Hp15: seed_225
ev_op_Hp20: seed_225
ev_op_Hp25: seed_225
ev_op_Hp30: seed_0
ev_op_Hp15_2f: seed_0
ev_op_Hp20_2f: seed_225
ev_op_Hp25_2f: seed_225
ev_op_Hp30_2f: seed_225
file saved as results_tests/l1.0_last_val_best.csv

In [145]:
l10_collate_v2.df_last_best

               cobyla_values  spsa_values
name
ev_op_Hp15           3.62082      3.67193
ev_op_Hp20           3.84073      3.60327
ev_op_Hp25           3.53512      3.96745
ev_op_Hp30           3.77387      3.54551
ev_op_Hp15_2f        4.35314      3.71765
ev_op_Hp20_2f        3.75998      3.59577
ev_op_Hp25_2f        4.92616      3.68810
ev_op_Hp30_2f        4.75916      3.63468

In [147]:
l10_collate_v2.df_last_best - E_10

               cobyla_values  spsa_values
name
ev_op_Hp15           0.09457      0.14568
ev_op_Hp20           0.31448      0.07702
ev_op_Hp25           0.00887      0.44120
ev_op_Hp30           0.24762      0.01926
ev_op_Hp15_2f        0.82689      0.19140
ev_op_Hp20_2f        0.23373      0.06952
ev_op_Hp25_2f        1.39991      0.16185
ev_op_Hp30_2f        1.23291      0.10843

In [149]:
l10_collate_v2.df_c_best.to_csv('results/l_10_cobyla_curves_values.csv')
l10_collate_v2.df_s_best.to_csv('results/l_10_spsa_curves_values.csv')

# l = 2.0

In [18]:
#Correct results
df_l20 = pd.read_csv('results/l2.0_last_val_best.csv')
df_l20_c = pd.read_csv('results/l_20_cobyla_curves_values.csv')
df_l20_s = pd.read_csv('results/l_20_spsa_curves_values.csv')
df_l20.set_index('name', inplace = True)

In [19]:
df_20c_170 = load_drop('results_seeds/l4_l20_op_ev_20_30_40_indv_cobyla.csv')
df_20s_170 = load_drop('results_seeds/l4_l20_op_ev_20_30_40_indv_spsa.csv')
df_20c_225 = load_drop('results_seeds/l4_l20_op_ev_cobyla_seed225.csv')
df_20s_225 = load_drop('results_seeds/l4_l20_op_ev_spsa_seed225.csv')

In [20]:
l20_collate = EvOpAnsatz_data_collate(df_20c_170, df_20c_225, df_20s_170, df_20s_225, 170, 225, E_20, 2.0)

file saved as results_tests/l2.0_last_val_170.csv
file saved as results_tests/l2.0_last_val_225.csv
Checking COBYLA column
ev_op_Hp15: seed_225
ev_op_Hp20: seed_225
ev_op_Hp25: seed_170
ev_op_Hp30: seed_170
ev_op_Hp15_2f: seed_225
ev_op_Hp20_2f: seed_225
ev_op_Hp25_2f: seed_170
ev_op_Hp30_2f: seed_170
Checking SPSA column
ev_op_Hp15: seed_225
ev_op_Hp20: seed_225
ev_op_Hp25: seed_225
ev_op_Hp30: seed_225
ev_op_Hp15_2f: seed_225
ev_op_Hp20_2f: seed_170
ev_op_Hp25_2f: seed_225
ev_op_Hp30_2f: seed_170
file saved as results_tests/l2.0_last_val_best.csv

In [21]:
l20_collate.df_last_best - df_l20

               cobyla_values  spsa_values
name
ev_op_Hp15               0.0          0.0
ev_op_Hp20               0.0          0.0
ev_op_Hp25               0.0          0.0
ev_op_Hp30               0.0          0.0
ev_op_Hp15_2f            0.0          0.0
ev_op_Hp20_2f            0.0          0.0
ev_op_Hp25_2f            0.0          0.0
ev_op_Hp30_2f            0.0          0.0

In [22]:
#l20_collate.df_c_best - df_l20_c

In [23]:
#l20_collate.df_s_best - df_l20_s