# Lambda = 4: Rerun some ansatzes w different seeds

Notebook created by HLD for the work arXiv: 2503.13368 [quant-ph, hep-th]

In this notebook, we rerun some of the VQE experiments for bosonic SU(2) matrix model at $\Lambda = 4$ (using different variants of EvolvedOperatorAnsatz) at different Estimator seeds.

In [1]:
#pip install qiskit = 1.3.0
#pip install qiskit_aer = 0.15
import sys
sys.path.append('../../utility')
from vqe_run import *
from qc_ansatze import *
from L4_evop_func import *

# VQE individual runs

In [2]:
#storing values
counts = []
values = []
def store_intermediate_result(eval_count, parameters, mean, std):
    counts.append(eval_count)
    values.append(mean)
    
def run_qve_w_specified_optimizer(optimizer, ansatz, iters, seed):
    algorithm_globals.random_seed = seed
    #estimator
    noiseless_estimator = AerEstimator(
        run_options={"seed": seed, "shots": 1024},
        transpile_options={"seed_transpiler": seed})
    opt = optimizer(maxiter = iters)
    vqe = VQE(noiseless_estimator, ansatz, optimizer=opt, callback=store_intermediate_result)
    result = vqe.compute_minimum_eigenvalue(operator=H4q).eigenvalue.real
    print(f"VQE result: {result:.5f}")
    return result

In [25]:
seeds_list_1 = [28, 170, 225, 188]
seeds_list_2 = np.arange(10, 15)
seeds = []
[seeds.append(seeds_list_1[i]) for i in range(len(seeds_list_1))]
[seeds.append(seeds_list_2[i]) for i in range(len(seeds_list_2))]
seeds

[28, 170, 225, 188, 10, 11, 12, 13, 14]

#  lambda = 0.2: ev_op_Hp15 (COBYLA)

In [37]:
l4_l02_evop = L4_evop(0.2)

Min absolute value is 0.000897
Max absolute value is 1.15
Mean absolute value is 0.03431
None
E_exact = 3.13406

In [39]:
H4q = l4_l02_evop.H4q

In [41]:
l4_l02_evop.ansatz_list[0], l4_l02_evop.ansatz_names[0]

(<qiskit.circuit.library.n_local.evolved_operator_ansatz.EvolvedOperatorAnsatz at 0x13aa17890>,
 'ev_op_Hp15')

In [43]:
r_cobyla=[]
seeds = [28, 170, 225, 188, 18, 38, 48, 58]
for i in range(len(seeds)):
    print(f'At step {i}, with {seeds[i]}')
    counts = []
    values = []
    t0 = time.time()
    result = run_qve_w_specified_optimizer(COBYLA, l4_l02_evop.ansatz_list[0], seeds[i], 650)
    t1 = time.time()
    print(f'Length of this optimization {len(values)}, time taken = {np.round(t1-t0,3)} \n')
    counts_a = counts
    values_a = values 
    r_cobyla.append(pd.DataFrame({f'seed_{seeds[i]}': values_a}))

At step 0, with 28
VQE result: 3.27813
Length of this optimization 28, time taken = 28.436

At step 1, with 170
VQE result: 3.09295
Length of this optimization 159, time taken = 124.97

At step 2, with 225
VQE result: 3.09295
Length of this optimization 159, time taken = 123.019

At step 3, with 188
VQE result: 3.09295
Length of this optimization 159, time taken = 120.742

At step 4, with 18
VQE result: 5.06867
Length of this optimization 18, time taken = 19.666

At step 5, with 38
VQE result: 3.27813
Length of this optimization 38, time taken = 34.221

At step 6, with 48
VQE result: 3.15174
Length of this optimization 48, time taken = 41.182

At step 7, with 58
VQE result: 3.10768
Length of this optimization 58, time taken = 48.373

In [44]:
df1 = pd.concat([r_cobyla[i] for i in range(len(r_cobyla))], axis = 1)
df1.to_csv('results_seeds/l4_l02_op_ev_Hp15_cobyla_seeds.csv')

In [45]:
df1

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58
0,5.289854,5.289854,5.289854,5.289854,5.289854,5.289854,5.289854,5.289854
1,6.052138,6.052138,6.052138,6.052138,6.052138,6.052138,6.052138,6.052138
2,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102
3,7.040846,7.040846,7.040846,7.040846,7.040846,7.040846,7.040846,7.040846
4,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102,5.155102
...,...,...,...,...,...,...,...,...
154,NaN,3.090015,3.090015,3.090015,NaN,NaN,NaN,NaN
155,NaN,3.089287,3.089287,3.089287,NaN,NaN,NaN,NaN
156,NaN,3.088952,3.088952,3.088952,NaN,NaN,NaN,NaN
157,NaN,3.094078,3.094078,3.094078,NaN,NaN,NaN,NaN
158,NaN,3.092946,3.092946,3.092946,NaN,NaN,NaN,NaN

#  lambda = 0.5: ev_op_Hp20 (COBYLA)

In [46]:
l4_l05_evop = L4_evop(0.5)

Min absolute value is 0.002244
Max absolute value is 1.375
Mean absolute value is 0.07067
None
E_exact = 3.29894

In [47]:
H4q = l4_l05_evop.H4q

In [48]:
l4_l05_evop.ansatz_list[1], l4_l05_evop.ansatz_names[1]

(<qiskit.circuit.library.n_local.evolved_operator_ansatz.EvolvedOperatorAnsatz at 0x13aa48140>,
 'ev_op_Hp20')

In [49]:
r_cobyla=[]
seeds = [28, 170, 225, 188, 18, 38, 48, 58]
for i in range(len(seeds)):
    print(f'At step {i}, with {seeds[i]}')
    counts = []
    values = []
    t0 = time.time()
    result = run_qve_w_specified_optimizer(COBYLA, l4_l05_evop.ansatz_list[1], seeds[i], 650)
    t1 = time.time()
    print(f'Length of this optimization {len(values)}, time taken = {np.round(t1-t0,3)} \n')
    counts_a = counts
    values_a = values 
    r_cobyla.append(pd.DataFrame({f'seed_{seeds[i]}': values_a}))

At step 0, with 28
VQE result: 7.64992
Length of this optimization 28, time taken = 32.7

At step 1, with 170
VQE result: 3.26323
Length of this optimization 170, time taken = 165.777

At step 2, with 225
VQE result: 3.24763
Length of this optimization 225, time taken = 213.43

At step 3, with 188
VQE result: 3.24763
Length of this optimization 188, time taken = 180.616

At step 4, with 18
VQE result: 9.87610
Length of this optimization 18, time taken = 24.145

At step 5, with 38
VQE result: 4.90023
Length of this optimization 38, time taken = 43.048

At step 6, with 48
VQE result: 4.84944
Length of this optimization 48, time taken = 51.716

At step 7, with 58
VQE result: 4.61082
Length of this optimization 58, time taken = 64.883

In [50]:
df2 = pd.concat([r_cobyla[i] for i in range(len(r_cobyla))], axis = 1)
df2.to_csv('results_seeds/l4_l05_op_ev_Hp20_cobyla_seeds.csv')

In [51]:
df2

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58
0,14.723072,14.723072,14.723072,14.723072,14.723072,14.723072,14.723072,14.723072
1,14.395842,14.395842,14.395842,14.395842,14.395842,14.395842,14.395842,14.395842
2,14.096420,14.096420,14.096420,14.096420,14.096420,14.096420,14.096420,14.096420
3,14.569231,14.569231,14.569231,14.569231,14.569231,14.569231,14.569231,14.569231
4,14.948990,14.948990,14.948990,14.948990,14.948990,14.948990,14.948990,14.948990
...,...,...,...,...,...,...,...,...
220,NaN,NaN,3.249845,NaN,NaN,NaN,NaN,NaN
221,NaN,NaN,3.331850,NaN,NaN,NaN,NaN,NaN
222,NaN,NaN,3.264188,NaN,NaN,NaN,NaN,NaN
223,NaN,NaN,3.253605,NaN,NaN,NaN,NaN,NaN
224,NaN,NaN,3.266912,NaN,NaN,NaN,NaN,NaN

# lambda=1.0: ev_op_Hp25 (SPSA)

In [52]:
l4_l10_evop = L4_evop(1.0)

Min absolute value is 0.004487
Max absolute value is 1.75
Mean absolute value is 0.13128
None
E_exact = 3.52625

In [53]:
H4q = l4_l10_evop.H4q

In [54]:
l4_l10_evop.ansatz_list[2], l4_l10_evop.ansatz_names[2]

(<qiskit.circuit.library.n_local.evolved_operator_ansatz.EvolvedOperatorAnsatz at 0x13d02b7d0>,
 'ev_op_Hp25')

In [55]:
r_spsa=[]
ansatz_rerun= l4_l10_evop.ansatz_list[2]
seeds = [28, 170, 225, 188, 18, 38, 48, 58]
for i in range(len(seeds)):
    print(f'At step {i}, with {seeds[i]}')
    counts = []
    values = []
    t0 = time.time()
    result = run_qve_w_specified_optimizer(SPSA, ansatz_rerun, seeds[i], 650)
    t1 = time.time()
    print(f'Length of this optimization {len(values)}, time taken = {np.round(t1-t0,3)} \n')
    counts_a = counts
    values_a = values 
    r_spsa.append(pd.DataFrame({f'seed_{seeds[i]}': values_a}))

At step 0, with 28
VQE result: 4.69473
Length of this optimization 107, time taken = 436.025

At step 1, with 170
VQE result: 3.40026
Length of this optimization 391, time taken = 691.284

At step 2, with 225
VQE result: 3.52580
Length of this optimization 501, time taken = 787.39

At step 3, with 188
VQE result: 3.27797
Length of this optimization 427, time taken = 720.797

At step 4, with 18
VQE result: 7.06349
Length of this optimization 87, time taken = 413.067

At step 5, with 38
VQE result: 4.38076
Length of this optimization 127, time taken = 440.291

At step 6, with 48
VQE result: 3.96745
Length of this optimization 147, time taken = 473.744

At step 7, with 58
VQE result: 3.50736
Length of this optimization 167, time taken = 503.113

In [56]:
df3 = pd.concat([r_spsa[i] for i in range(len(r_spsa))], axis = 1)
df3.to_csv('results_seeds/l4_l10_op_ev_Hp25_spsa_seeds.csv')

In [57]:
df3

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58
0,23.239583,23.239583,23.239583,23.239583,23.239583,23.239583,23.239583,23.239583
1,19.621141,19.621141,19.621141,19.621141,19.621141,19.621141,19.621141,19.621141
2,20.328117,20.328117,20.328117,20.328117,20.328117,20.328117,20.328117,20.328117
3,21.217278,21.217278,21.217278,21.217278,21.217278,21.217278,21.217278,21.217278
4,18.859880,18.859880,18.859880,18.859880,18.859880,18.859880,18.859880,18.859880
...,...,...,...,...,...,...,...,...
496,NaN,NaN,4.169581,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,3.978447,NaN,NaN,NaN,NaN,NaN
498,NaN,NaN,3.992127,NaN,NaN,NaN,NaN,NaN
499,NaN,NaN,4.221231,NaN,NaN,NaN,NaN,NaN
500,NaN,NaN,3.525798,NaN,NaN,NaN,NaN,NaN