# Supersymmetric SU2 matrix model, Lambda =2: Data processing

Notebook created by HLD for the work arXiv: 2503.13368 [quant-ph, hep-th]

In [1]:
import sys
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
E_02 = 0.003287
E_05 = 0.01690
E_10 = 0.04829
E_20 = 0.08385
def find_best_ansatz(df, Ee):
    c_i = np.argmin(np.abs(df['cobyla_values']- Ee))
    print(f'Exact energy is {Ee}')
    print(f'Best ansatz for COBYLA is {df.index[c_i]} with value: {df.cobyla_values[c_i]}')
    s_i = np.argmin(np.abs(df['spsa_values']- Ee))
    print(f'Best ansatz for SPSA is {df.index[s_i]} with value: {df.spsa_values[s_i]}')
    diff_c = np.abs(df.cobyla_values[c_i]-Ee)
    diff_s = np.abs(df.spsa_values[s_i]-Ee)
    if diff_c < diff_s:
        print(f'Best ansatz overall is {df.index[c_i]}')
    if diff_c > diff_s:
         print(f'Best ansatz overall is {df.index[s_i]}')

In [3]:
def load_drop(link, name = False):
    df = pd.read_csv(link)
    df.drop(['Unnamed: 0'], axis = 1, inplace=True)
    return df

def set_name_index(link):
    df = pd.read_csv(link)
    df.set_index('name', inplace=True)
    return df

In [7]:
def choose_best_seed(df, Ee):
    lv = []
    if df.columns[0] == 'Unnamed: 0':
        df.drop(df.columns[0], axis = 1, inplace = True)
    for i in range(len(df.columns)):
        last_v = df[df.columns[i]].to_numpy()[-1]
        lv_e = last_v - Ee
        if lv_e >0:
            lv.append(lv_e)
        else:
            lv.append(2.0)
    b_v = np.argmin(lv)
    
    return df.columns[b_v], df[df.columns[b_v]].to_numpy()[-1]

# Load old data

In [9]:
#OLD DATA FROM FISRT RUNS USING A SINGLE SEED

df_02s= load_drop('results/L2_l02_op_ev_spsa.csv')
df_05s= load_drop('results/L2_l05_op_ev_spsa.csv')
df_10s =load_drop('results/L2_l10_op_ev_spsa.csv')
df_20s= load_drop('results/L2_l20_op_ev_spsa.csv')

In [8]:
# NEW DATA FROM NEW RUNS (MULTIPLE SEEDS)

In [11]:
df_l02o = set_name_index('results/l02_last_val_ev_op.csv')
df_l05o = set_name_index('results/l05_last_val_ev_op.csv')
df_l10o = set_name_index('results/l10_last_val_ev_op.csv')
df_l20o = set_name_index('results/l20_last_val_ev_op.csv')

# lambda = 0.2

In [13]:
find_best_ansatz(df_l02o, E_02)

Exact energy is 0.003287
Best ansatz for COBYLA is ev_op_H_2f with value: 0.03099
Best ansatz for SPSA is ev_op_Hp20 with value: 0.01228
Best ansatz overall is ev_op_Hp20

In [15]:
dfa = load_drop('results_seeds/l2_l02_evopHp20_spsa_seeds.csv')
dfb = load_drop('results_seeds/l2_l02_evopHp20_spsa_seeds_2.csv')
df02 = pd.concat([dfa, dfb], axis = 1)
df02

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58,seed_245,seed_198,seed_148,seed_138,seed_158,seed_128
0,5.006652,5.231595,5.671191,5.547886,6.201684,5.816877,4.934758,5.503205,6.681398,5.475123,5.838922,5.144600,5.190287,5.368070
1,5.597869,6.015377,4.722595,5.809189,6.813614,5.034101,5.421319,6.400881,7.046836,5.137104,4.962923,5.172101,5.102554,5.855362
2,6.054368,5.234771,5.149964,7.029068,6.935638,5.547617,4.583732,6.578650,6.657818,5.322754,5.331561,5.600803,4.959723,5.617983
3,5.486298,5.858079,6.110811,4.868089,5.945622,5.606117,5.502588,5.422978,6.752674,5.887623,5.553251,4.844007,4.916452,4.955411
4,4.957220,4.938866,4.970122,6.549505,7.556715,5.815446,6.547099,6.573661,7.049381,5.633368,5.980150,4.781248,5.359950,6.600177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4046,0.402229,2.650673,0.343520,0.443042,2.200462,2.411441,3.404314,0.290564,0.209171,0.547219,0.656404,0.332245,0.532191,2.297325
4047,0.362892,2.544651,0.327795,0.445488,2.231904,2.378140,3.325660,0.383262,0.241249,0.459161,0.572182,0.297099,0.375296,2.307246
4048,0.628283,2.431415,0.323068,0.361108,2.286681,2.307286,3.172541,0.600707,0.348047,0.542717,0.241593,0.482881,0.454769,2.224529
4049,0.519682,2.397412,0.353133,0.379227,2.245423,2.320781,3.143341,0.731530,0.329560,0.525007,0.146713,0.335624,0.452292,2.197317
4050,0.013792,1.996910,-0.003160,-0.038199,1.935028,2.027523,3.032281,0.047124,-0.004014,0.052311,0.043338,0.024270,0.048759,2.020459

In [17]:
choose_best_seed(df02, E_02)

('seed_28', 0.013792462243118)

In [19]:
df_02s.to_csv('results/L2_l02_op_ev_spsa_best.csv')

# lambda = 0.5

In [21]:
find_best_ansatz(df_l05o, E_05)

Exact energy is 0.0169
Best ansatz for COBYLA is ev_op_Hp15_2f with value: 0.19482
Best ansatz for SPSA is ev_op_Hp20 with value: 0.03564
Best ansatz overall is ev_op_Hp20

In [23]:
dfa = load_drop('results_seeds/l2_l05_evopHp20_spsa_seeds.csv')
dfb = load_drop('results_seeds/l2_l05_evopHp20_spsa_seeds_2.csv')
df05 = pd.concat([dfa, dfb], axis = 1)
df05

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58,seed_245,seed_198,seed_148,seed_138,seed_158,seed_128
0,5.165527,5.420898,5.899414,5.686523,6.434082,6.009277,5.101562,5.669434,6.829590,5.719727,5.976562,5.448730,5.453613,5.585938
1,5.757812,6.201660,4.854492,6.018066,7.020020,5.312988,5.616699,6.625977,7.403809,5.502441,5.197266,5.428711,5.294434,5.989746
2,6.239746,5.473633,5.296875,7.305176,7.193359,5.790039,4.739258,6.740234,6.888672,5.594727,5.537109,5.860352,5.213867,5.806152
3,5.646973,5.988770,6.343750,5.028809,6.175293,5.895508,5.596680,5.612305,6.983887,6.144043,5.788574,5.126953,5.150879,5.106445
4,5.043457,5.204102,5.087402,6.708496,7.782715,6.018555,6.754395,6.711426,7.392578,5.850098,6.253906,4.947266,5.539062,6.838867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4046,0.416504,2.383301,0.580078,0.527344,3.436035,0.385742,3.438477,0.390625,0.361328,0.603516,2.227539,0.626953,0.495605,0.644531
4047,0.358398,2.372559,0.599609,0.625977,3.387695,0.438965,3.393555,0.559570,0.474609,0.508301,2.171875,0.485352,0.317871,0.670898
4048,0.635742,2.425293,0.584961,0.418945,3.337402,0.308594,3.292969,0.673340,0.299805,0.527344,2.617676,0.634766,0.681641,0.245117
4049,0.639160,2.414062,0.593262,0.459961,3.259277,0.266602,3.174805,0.811523,0.253418,0.583984,2.625000,0.532715,0.741211,0.334961
4050,0.051758,1.995605,0.061523,-0.013672,2.965820,0.061523,3.038574,0.040527,0.019531,0.083496,1.950195,0.126953,0.084473,0.054199

In [25]:
choose_best_seed(df05, E_05)

('seed_245', 0.01953125)

In [27]:
df_05s['ev_op_Hp20'] = df05['seed_245']
df_05s.to_csv('results/L2_l05_op_ev_spsa_best.csv')

# lambda = 1.0

In [29]:
find_best_ansatz(df_l10o, E_10)

Exact energy is 0.04829
Best ansatz for COBYLA is ev_op_Hp15_3f with value: 0.39722
Best ansatz for SPSA is ev_op_Hp20 with value: 0.13208
Best ansatz overall is ev_op_Hp20

In [31]:
dfa = load_drop('results_seeds/l2_l10_evopHp20_spsa_seeds.csv')
dfb = load_drop('results_seeds/l2_l10_evopHp20_spsa_seeds_2.csv')
df10 = pd.concat([dfa, dfb], axis = 1)
df10

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58,seed_245,seed_198,seed_148,seed_138,seed_158,seed_128
0,5.469643,5.744443,6.279785,5.962140,6.819475,6.344376,5.399910,5.986580,7.121033,6.111127,6.255166,5.908639,5.867695,5.960963
1,6.054119,6.533343,5.126623,6.375687,7.387662,5.749034,5.960058,7.001716,7.927381,6.040341,5.584060,5.844869,5.646971,6.266893
2,6.572149,5.869314,5.581341,7.735717,7.606816,6.188942,5.033432,7.036177,7.267422,6.022347,5.887342,6.261163,5.616810,6.137590
3,5.948373,6.252109,6.732757,5.327571,6.550813,6.344024,5.812291,5.949157,7.363042,6.558722,6.183588,5.564727,5.537136,5.400301
4,5.244524,5.631245,5.328197,7.005152,8.157735,6.371887,7.106280,6.991592,7.905684,6.219255,6.682272,5.260379,5.860925,7.232616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4046,0.718245,0.423334,0.515622,0.731160,0.779597,0.577513,2.665612,0.653089,0.408263,2.596877,0.909761,0.686392,0.602759,0.690228
4047,0.765148,0.480173,0.585960,0.555780,0.627546,0.556873,2.601331,0.779614,0.506092,2.603685,0.898394,0.585246,0.516788,0.700972
4048,0.956362,0.648162,0.471279,0.518117,0.771438,0.461197,2.383644,0.674056,0.340837,2.515069,0.529107,0.780125,0.803003,0.481943
4049,1.039543,0.551611,0.646139,0.438854,0.727361,0.441988,2.457721,0.739801,0.437539,2.466446,0.380881,0.598866,0.859807,0.523079
4050,0.215069,0.145652,0.112434,0.001391,0.102290,0.154294,2.061689,0.222793,0.109976,2.252954,0.130315,0.217384,0.138951,0.131257

In [35]:
choose_best_seed(df10, E_10)

('seed_18', 0.1022904490343752)

In [37]:
df_10s['ev_op_Hp20'] = df10['seed_18']
df_10s.to_csv('results/L2_l10_op_ev_spsa_best.csv')

# lambda =2.0

In [39]:
find_best_ansatz(df_l20o, E_20)

Exact energy is 0.08385
Best ansatz for COBYLA is ev_op_Hp20_3f with value: 0.625
Best ansatz for SPSA is ev_op_Hp20 with value: 0.20508
Best ansatz overall is ev_op_Hp20

In [41]:
dfa = load_drop('results_seeds/l2_l20_evopHp20_spsa_seeds.csv')
dfb = load_drop('results_seeds/l2_l20_evopHp20_spsa_seeds_2.csv')
df20 = pd.concat([dfa, dfb], axis = 1)
df20

,seed_28,seed_170,seed_225,seed_188,seed_18,seed_38,seed_48,seed_58,seed_245,seed_198,seed_148,seed_138,seed_158,seed_128
0,6.125977,6.401367,7.040527,6.567871,7.587891,7.032227,6.021484,6.669922,7.758301,6.874023,6.872559,6.770996,6.665527,6.725586
1,6.683105,7.222656,5.734863,7.102539,8.151855,6.585938,6.668457,7.753906,8.887207,7.029297,6.353027,6.663086,6.392090,6.886230
2,7.265625,6.657715,6.198730,8.560547,8.414062,6.980469,5.664551,7.660645,8.017578,6.846191,6.597168,7.023926,6.397461,6.822266
3,6.592285,6.834473,7.511719,5.962891,7.292969,7.199707,6.315430,6.648926,8.113770,7.372559,6.977051,6.398926,6.304199,6.039551
4,5.716797,6.467285,5.865234,7.637207,8.905762,7.096680,7.817871,7.613770,8.859863,6.967285,7.504883,5.931152,6.533203,8.015137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4046,2.720215,0.863770,0.893555,1.031250,0.943848,0.855469,4.235352,1.076172,0.803711,1.106445,2.864746,1.240723,0.984863,0.769043
4047,2.550293,0.812500,1.117188,0.889648,0.930664,0.974609,4.110352,1.211914,0.826660,0.961914,2.783203,0.992188,0.994141,0.946289
4048,2.498047,1.134766,0.848145,0.826172,1.143066,0.769043,3.995117,1.075195,0.597656,0.797852,2.374023,0.877441,1.082520,0.791992
4049,2.557129,0.993652,1.051270,0.850586,0.973145,0.816895,3.940430,1.075684,0.616211,0.862305,2.331543,0.854980,1.065430,0.947266
4050,2.243164,0.329102,0.353516,0.159180,0.291016,0.304688,3.766113,0.545410,0.346191,0.444824,2.092285,0.418457,0.348633,0.431641

In [45]:
choose_best_seed(df20, E_20)

('seed_188', 0.1591796875000001)

In [47]:
df_20s['ev_op_Hp20'] = df20['seed_188']
df_20s.to_csv('results/L2_l20_op_ev_spsa_best.csv')